drop table if exists orders CASCADE;
create table orders
(
id bigint generated by default as identity,
product_id varchar(255),
qty integer ,
unit_price integer ,
total_price integer ,
user_id varchar(255) ,
order_id varchar(255) ,
created_at date default CURRENT_TIMESTAMP(),
primary key (id)
);
