drop table if exists users CASCADE;
create table users
(
id bigint generated by default as identity,
name varchar(255),
pwd varchar(255),
user_id varchar(255),
email varchar(255),
created_at date,
primary key (id)
);
